services:
    application:
        build: 
            dockerfile: ./Dockerfile

        command: uvicorn main:app --host 0.0.0.0 --port 80
        
        ports:
          - 80:80

        depends_on:
          - db
        
        env_file:
            - "./.env"

    db:
        image: postgres
    
        volumes:
            - ./pgdata:/var/lib/postgresql/data

        expose:
          - 5432

        env_file:
            - "./.env"

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4

        depends_on:
            - db

        environment:
            PGADMIN_CONFIG_SERVER_MODE: 'False'

        volumes:
            - ./pgadmin:/var/lib/pgadmin

        ports:
            - "105:80"


        restart: unless-stopped

        env_file:
            - "./.env"

